package store

var sqliteMigrations = []string{
	`CREATE TABLE IF NOT EXISTS users (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		username TEXT NOT NULL UNIQUE,
		password_hash TEXT NOT NULL,
		must_change_password INTEGER NOT NULL DEFAULT 1,
		failed_attempts INTEGER NOT NULL DEFAULT 0,
		locked_until DATETIME NULL,
		last_login_at DATETIME NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS sessions (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		user_id INTEGER NOT NULL,
		token_digest TEXT NOT NULL UNIQUE,
		expires_at DATETIME NOT NULL,
		created_at DATETIME NOT NULL,
		last_seen_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS login_attempts (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		username TEXT NOT NULL,
		ip_address TEXT NOT NULL,
		failed_attempts INTEGER NOT NULL DEFAULT 0,
		locked_until DATETIME NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL,
		UNIQUE(username, ip_address)
	)`,
	`CREATE TABLE IF NOT EXISTS policies (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		subnet_ocid TEXT NOT NULL DEFAULT '',
		shape TEXT NOT NULL,
		ocpu INTEGER NOT NULL,
		memory_gb INTEGER NOT NULL,
		max_runners INTEGER NOT NULL,
		ttl_minutes INTEGER NOT NULL,
		spot INTEGER NOT NULL DEFAULT 0,
		enabled INTEGER NOT NULL DEFAULT 1,
		warm_enabled INTEGER NOT NULL DEFAULT 0,
		warm_min_idle INTEGER NOT NULL DEFAULT 0,
		warm_ttl_minutes INTEGER NOT NULL DEFAULT 0,
		warm_repo_allowlist_json TEXT NOT NULL DEFAULT '[]',
		budget_enabled INTEGER NOT NULL DEFAULT 0,
		budget_cap_amount REAL NOT NULL DEFAULT 0,
		budget_window_days INTEGER NOT NULL DEFAULT 7,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS policy_labels (
		policy_id INTEGER NOT NULL,
		label TEXT NOT NULL,
		UNIQUE(policy_id, label)
	)`,
	`CREATE TABLE IF NOT EXISTS jobs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		github_job_id INTEGER NOT NULL UNIQUE,
		delivery_id TEXT NOT NULL,
		installation_id INTEGER NOT NULL DEFAULT 0,
		github_config_id INTEGER NOT NULL DEFAULT 0,
		github_config_name TEXT NOT NULL DEFAULT '',
		github_config_tags_json TEXT NOT NULL DEFAULT '[]',
		repo_owner TEXT NOT NULL,
		repo_name TEXT NOT NULL,
		run_id INTEGER NOT NULL DEFAULT 0,
		run_attempt INTEGER NOT NULL DEFAULT 1,
		status TEXT NOT NULL,
		labels_json TEXT NOT NULL,
		matched_policy_id INTEGER NULL,
		error_message TEXT NOT NULL DEFAULT '',
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS runners (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		policy_id INTEGER NOT NULL,
		job_id INTEGER NOT NULL,
		installation_id INTEGER NOT NULL DEFAULT 0,
		github_config_id INTEGER NOT NULL DEFAULT 0,
		github_config_name TEXT NOT NULL DEFAULT '',
		github_config_tags_json TEXT NOT NULL DEFAULT '[]',
		instance_ocid TEXT NOT NULL,
		github_runner_id INTEGER NOT NULL DEFAULT 0,
		repo_owner TEXT NOT NULL,
		repo_name TEXT NOT NULL,
		runner_name TEXT NOT NULL,
		status TEXT NOT NULL,
		labels_json TEXT NOT NULL,
		source TEXT NOT NULL DEFAULT 'ondemand',
		warm_state TEXT NOT NULL DEFAULT '',
		warm_policy_id INTEGER NULL,
		warm_repo_owner TEXT NOT NULL DEFAULT '',
		warm_repo_name TEXT NOT NULL DEFAULT '',
		launched_at DATETIME NULL,
		expires_at DATETIME NULL,
		terminated_at DATETIME NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS events (
		delivery_id TEXT PRIMARY KEY,
		event_type TEXT NOT NULL,
		action TEXT NOT NULL,
		repo_owner TEXT NOT NULL,
		repo_name TEXT NOT NULL,
		payload_json TEXT NOT NULL,
		processed_at DATETIME NULL,
		created_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS event_logs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		delivery_id TEXT NULL,
		level TEXT NOT NULL,
		message TEXT NOT NULL,
		details_json TEXT NOT NULL DEFAULT '',
		created_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS oci_credentials (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL,
		profile_name TEXT NULL,
		tenancy_ocid TEXT NOT NULL,
		user_ocid TEXT NOT NULL,
		fingerprint TEXT NOT NULL,
		region TEXT NOT NULL,
		private_key_ciphertext TEXT NOT NULL,
		passphrase_ciphertext TEXT NOT NULL DEFAULT '',
		is_active INTEGER NOT NULL DEFAULT 0,
		last_tested_at DATETIME NULL,
		last_test_error TEXT NOT NULL DEFAULT '',
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS oci_runtime_settings (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		compartment_ocid TEXT NOT NULL DEFAULT '',
		availability_domain TEXT NOT NULL DEFAULT '',
		subnet_ocid TEXT NOT NULL DEFAULT '',
		nsg_ocids_json TEXT NOT NULL DEFAULT '[]',
		image_ocid TEXT NOT NULL DEFAULT '',
		assign_public_ip INTEGER NOT NULL DEFAULT 0,
		cache_compat_enabled INTEGER NOT NULL DEFAULT 0,
		cache_bucket_name TEXT NOT NULL DEFAULT '',
		cache_object_prefix TEXT NOT NULL DEFAULT '',
		cache_retention_days INTEGER NOT NULL DEFAULT 7,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS github_configs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL DEFAULT '',
		tags_json TEXT NOT NULL DEFAULT '[]',
		api_base_url TEXT NOT NULL DEFAULT '',
		auth_mode TEXT NOT NULL DEFAULT 'app',
		app_id INTEGER NOT NULL DEFAULT 0,
		installation_id INTEGER NOT NULL DEFAULT 0,
		private_key_ciphertext TEXT NOT NULL,
		webhook_secret_ciphertext TEXT NOT NULL,
		allowed_org TEXT NOT NULL DEFAULT '',
		allowed_repos_json TEXT NOT NULL DEFAULT '[]',
		account_login TEXT NOT NULL DEFAULT '',
		account_type TEXT NOT NULL DEFAULT '',
		installation_state TEXT NOT NULL DEFAULT '',
		installation_repository_selection TEXT NOT NULL DEFAULT '',
		installation_repositories_json TEXT NOT NULL DEFAULT '[]',
		is_active INTEGER NOT NULL DEFAULT 0,
		is_staged INTEGER NOT NULL DEFAULT 0,
		last_tested_at DATETIME NULL,
		last_test_error TEXT NOT NULL DEFAULT '',
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS github_pending_manifests (
		session_binding TEXT NOT NULL UNIQUE,
		app_id INTEGER NOT NULL,
		app_name TEXT NOT NULL DEFAULT '',
		app_slug TEXT NOT NULL DEFAULT '',
		app_settings_url TEXT NOT NULL DEFAULT '',
		transfer_url TEXT NOT NULL DEFAULT '',
		install_url TEXT NOT NULL DEFAULT '',
		owner_target TEXT NOT NULL DEFAULT '',
		private_key_ciphertext TEXT NOT NULL,
		webhook_secret_ciphertext TEXT NOT NULL,
		created_at DATETIME NOT NULL,
		expires_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS github_route_installation_statuses (
		api_base_url TEXT NOT NULL,
		app_id INTEGER NOT NULL DEFAULT 0,
		installation_id INTEGER NOT NULL DEFAULT 0,
		account_login TEXT NOT NULL DEFAULT '',
		account_type TEXT NOT NULL DEFAULT '',
		installation_state TEXT NOT NULL DEFAULT '',
		installation_repository_selection TEXT NOT NULL DEFAULT '',
		installation_repositories_json TEXT NOT NULL DEFAULT '[]',
		last_tested_at DATETIME NULL,
		last_test_error TEXT NOT NULL DEFAULT '',
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL,
		PRIMARY KEY (api_base_url, app_id, installation_id)
	)`,
	`CREATE TABLE IF NOT EXISTS runner_image_recipes (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL UNIQUE,
		description TEXT NOT NULL DEFAULT '',
		base_image_ocid TEXT NOT NULL DEFAULT '',
		subnet_ocid TEXT NOT NULL DEFAULT '',
		shape TEXT NOT NULL,
		ocpu INTEGER NOT NULL,
		memory_gb INTEGER NOT NULL,
		image_display_name TEXT NOT NULL DEFAULT '',
		setup_commands_json TEXT NOT NULL DEFAULT '[]',
		verify_commands_json TEXT NOT NULL DEFAULT '[]',
		promoted_build_id INTEGER NULL,
		promoted_image_ocid TEXT NOT NULL DEFAULT '',
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS runner_image_builds (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		recipe_id INTEGER NOT NULL,
		recipe_name TEXT NOT NULL,
		status TEXT NOT NULL,
		status_message TEXT NOT NULL DEFAULT '',
		error_message TEXT NOT NULL DEFAULT '',
		base_image_ocid TEXT NOT NULL DEFAULT '',
		subnet_ocid TEXT NOT NULL DEFAULT '',
		shape TEXT NOT NULL,
		ocpu INTEGER NOT NULL,
		memory_gb INTEGER NOT NULL,
		image_display_name TEXT NOT NULL DEFAULT '',
		setup_commands_json TEXT NOT NULL DEFAULT '[]',
		verify_commands_json TEXT NOT NULL DEFAULT '[]',
		instance_ocid TEXT NOT NULL DEFAULT '',
		image_ocid TEXT NOT NULL DEFAULT '',
		launched_at DATETIME NULL,
		completed_at DATETIME NULL,
		promoted_at DATETIME NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`ALTER TABLE policies ADD COLUMN subnet_ocid TEXT NOT NULL DEFAULT ''`,
	`ALTER TABLE policies ADD COLUMN warm_enabled INTEGER NOT NULL DEFAULT 0`,
	`ALTER TABLE policies ADD COLUMN warm_min_idle INTEGER NOT NULL DEFAULT 0`,
	`ALTER TABLE policies ADD COLUMN warm_ttl_minutes INTEGER NOT NULL DEFAULT 0`,
	`ALTER TABLE policies ADD COLUMN warm_repo_allowlist_json TEXT NOT NULL DEFAULT '[]'`,
	`ALTER TABLE policies ADD COLUMN budget_enabled INTEGER NOT NULL DEFAULT 0`,
	`ALTER TABLE policies ADD COLUMN budget_cap_amount REAL NOT NULL DEFAULT 0`,
	`ALTER TABLE policies ADD COLUMN budget_window_days INTEGER NOT NULL DEFAULT 7`,
	`ALTER TABLE github_configs ADD COLUMN auth_mode TEXT NOT NULL DEFAULT 'app'`,
	`ALTER TABLE github_configs ADD COLUMN account_login TEXT NOT NULL DEFAULT ''`,
	`ALTER TABLE github_configs ADD COLUMN account_type TEXT NOT NULL DEFAULT ''`,
	`ALTER TABLE github_configs ADD COLUMN installation_state TEXT NOT NULL DEFAULT ''`,
	`ALTER TABLE github_configs ADD COLUMN installation_repository_selection TEXT NOT NULL DEFAULT ''`,
	`ALTER TABLE github_configs ADD COLUMN installation_repositories_json TEXT NOT NULL DEFAULT '[]'`,
	`ALTER TABLE github_configs ADD COLUMN is_staged INTEGER NOT NULL DEFAULT 0`,
	`ALTER TABLE github_configs ADD COLUMN name TEXT NOT NULL DEFAULT ''`,
	`ALTER TABLE github_configs ADD COLUMN tags_json TEXT NOT NULL DEFAULT '[]'`,
	`ALTER TABLE jobs ADD COLUMN github_config_id INTEGER NOT NULL DEFAULT 0`,
	`ALTER TABLE jobs ADD COLUMN github_config_name TEXT NOT NULL DEFAULT ''`,
	`ALTER TABLE jobs ADD COLUMN github_config_tags_json TEXT NOT NULL DEFAULT '[]'`,
	`ALTER TABLE runners ADD COLUMN github_config_id INTEGER NOT NULL DEFAULT 0`,
	`ALTER TABLE runners ADD COLUMN github_config_name TEXT NOT NULL DEFAULT ''`,
	`ALTER TABLE runners ADD COLUMN github_config_tags_json TEXT NOT NULL DEFAULT '[]'`,
	`ALTER TABLE runners ADD COLUMN source TEXT NOT NULL DEFAULT 'ondemand'`,
	`ALTER TABLE runners ADD COLUMN warm_state TEXT NOT NULL DEFAULT ''`,
	`ALTER TABLE runners ADD COLUMN warm_policy_id INTEGER NULL`,
	`ALTER TABLE runners ADD COLUMN warm_repo_owner TEXT NOT NULL DEFAULT ''`,
	`ALTER TABLE runners ADD COLUMN warm_repo_name TEXT NOT NULL DEFAULT ''`,
	`ALTER TABLE oci_runtime_settings ADD COLUMN cache_compat_enabled INTEGER NOT NULL DEFAULT 0`,
	`ALTER TABLE oci_runtime_settings ADD COLUMN cache_bucket_name TEXT NOT NULL DEFAULT ''`,
	`ALTER TABLE oci_runtime_settings ADD COLUMN cache_object_prefix TEXT NOT NULL DEFAULT ''`,
	`ALTER TABLE oci_runtime_settings ADD COLUMN cache_retention_days INTEGER NOT NULL DEFAULT 7`,
	`CREATE TABLE IF NOT EXISTS job_diagnostics (
		job_id INTEGER PRIMARY KEY,
		delivery_id TEXT NOT NULL DEFAULT '',
		summary_code TEXT NOT NULL DEFAULT '',
		blocking_stage TEXT NOT NULL DEFAULT '',
		matched_policy_id INTEGER NULL,
		runner_id INTEGER NULL,
		instance_ocid TEXT NOT NULL DEFAULT '',
		stage_statuses_json TEXT NOT NULL DEFAULT '{}',
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS billing_policy_snapshots (
		policy_id INTEGER NOT NULL,
		window_days INTEGER NOT NULL,
		currency TEXT NOT NULL DEFAULT '',
		total_cost REAL NOT NULL DEFAULT 0,
		generated_at DATETIME NOT NULL,
		source_region TEXT NOT NULL DEFAULT '',
		error_message TEXT NOT NULL DEFAULT '',
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL,
		PRIMARY KEY (policy_id, window_days)
	)`,
	`CREATE TABLE IF NOT EXISTS cache_entries (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		repo_owner TEXT NOT NULL,
		repo_name TEXT NOT NULL,
		cache_key TEXT NOT NULL,
		cache_version TEXT NOT NULL,
		object_name TEXT NOT NULL,
		size_bytes INTEGER NOT NULL DEFAULT 0,
		created_at DATETIME NOT NULL,
		last_accessed_at DATETIME NOT NULL,
		expires_at DATETIME NULL,
		UNIQUE (repo_owner, repo_name, cache_key, cache_version)
	)`,
	`CREATE TABLE IF NOT EXISTS http_rate_limits (
		scope TEXT NOT NULL,
		client_ip TEXT NOT NULL,
		window_started DATETIME NOT NULL,
		expires_at DATETIME NOT NULL,
		request_count INTEGER NOT NULL DEFAULT 0,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL,
		PRIMARY KEY (scope, client_ip, window_started)
	)`,
}

var mysqlMigrations = []string{
	`CREATE TABLE IF NOT EXISTS users (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		username VARCHAR(64) NOT NULL UNIQUE,
		password_hash VARCHAR(255) NOT NULL,
		must_change_password TINYINT(1) NOT NULL DEFAULT 1,
		failed_attempts INT NOT NULL DEFAULT 0,
		locked_until DATETIME NULL,
		last_login_at DATETIME NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS sessions (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		user_id BIGINT NOT NULL,
		token_digest VARCHAR(255) NOT NULL UNIQUE,
		expires_at DATETIME NOT NULL,
		created_at DATETIME NOT NULL,
		last_seen_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS login_attempts (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		username VARCHAR(64) NOT NULL,
		ip_address VARCHAR(128) NOT NULL,
		failed_attempts INT NOT NULL DEFAULT 0,
		locked_until DATETIME NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL,
		UNIQUE KEY login_attempts_username_ip (username, ip_address)
	)`,
	`CREATE TABLE IF NOT EXISTS policies (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		subnet_ocid VARCHAR(255) NOT NULL DEFAULT '',
		shape VARCHAR(128) NOT NULL,
		ocpu INT NOT NULL,
		memory_gb INT NOT NULL,
		max_runners INT NOT NULL,
		ttl_minutes INT NOT NULL,
		spot TINYINT(1) NOT NULL DEFAULT 0,
		enabled TINYINT(1) NOT NULL DEFAULT 1,
		warm_enabled TINYINT(1) NOT NULL DEFAULT 0,
		warm_min_idle INT NOT NULL DEFAULT 0,
		warm_ttl_minutes INT NOT NULL DEFAULT 0,
		warm_repo_allowlist_json LONGTEXT NOT NULL,
		budget_enabled TINYINT(1) NOT NULL DEFAULT 0,
		budget_cap_amount DOUBLE NOT NULL DEFAULT 0,
		budget_window_days INT NOT NULL DEFAULT 7,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS policy_labels (
		policy_id BIGINT NOT NULL,
		label VARCHAR(64) NOT NULL,
		UNIQUE KEY policy_labels_policy_label (policy_id, label)
	)`,
	`CREATE TABLE IF NOT EXISTS jobs (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		github_job_id BIGINT NOT NULL UNIQUE,
		delivery_id VARCHAR(128) NOT NULL,
		installation_id BIGINT NOT NULL DEFAULT 0,
		github_config_id BIGINT NOT NULL DEFAULT 0,
		github_config_name VARCHAR(255) NOT NULL DEFAULT '',
		github_config_tags_json LONGTEXT NOT NULL,
		repo_owner VARCHAR(128) NOT NULL,
		repo_name VARCHAR(128) NOT NULL,
		run_id BIGINT NOT NULL DEFAULT 0,
		run_attempt INT NOT NULL DEFAULT 1,
		status VARCHAR(64) NOT NULL,
		labels_json TEXT NOT NULL,
		matched_policy_id BIGINT NULL,
		error_message TEXT NOT NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS runners (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		policy_id BIGINT NOT NULL,
		job_id BIGINT NOT NULL,
		installation_id BIGINT NOT NULL DEFAULT 0,
		github_config_id BIGINT NOT NULL DEFAULT 0,
		github_config_name VARCHAR(255) NOT NULL DEFAULT '',
		github_config_tags_json LONGTEXT NOT NULL,
		instance_ocid VARCHAR(255) NOT NULL,
		github_runner_id BIGINT NOT NULL DEFAULT 0,
		repo_owner VARCHAR(128) NOT NULL,
		repo_name VARCHAR(128) NOT NULL,
		runner_name VARCHAR(255) NOT NULL,
		status VARCHAR(64) NOT NULL,
		labels_json TEXT NOT NULL,
		source VARCHAR(32) NOT NULL DEFAULT 'ondemand',
		warm_state VARCHAR(32) NOT NULL DEFAULT '',
		warm_policy_id BIGINT NULL,
		warm_repo_owner VARCHAR(128) NOT NULL DEFAULT '',
		warm_repo_name VARCHAR(128) NOT NULL DEFAULT '',
		launched_at DATETIME NULL,
		expires_at DATETIME NULL,
		terminated_at DATETIME NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS events (
		delivery_id VARCHAR(128) PRIMARY KEY,
		event_type VARCHAR(64) NOT NULL,
		action VARCHAR(64) NOT NULL,
		repo_owner VARCHAR(128) NOT NULL,
		repo_name VARCHAR(128) NOT NULL,
		payload_json LONGTEXT NOT NULL,
		processed_at DATETIME NULL,
		created_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS event_logs (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		delivery_id VARCHAR(128) NULL,
		level VARCHAR(16) NOT NULL,
		message TEXT NOT NULL,
		details_json LONGTEXT NOT NULL,
		created_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS oci_credentials (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		name VARCHAR(128) NOT NULL,
		profile_name VARCHAR(128) NULL,
		tenancy_ocid VARCHAR(255) NOT NULL,
		user_ocid VARCHAR(255) NOT NULL,
		fingerprint VARCHAR(255) NOT NULL,
		region VARCHAR(64) NOT NULL,
		private_key_ciphertext LONGTEXT NOT NULL,
		passphrase_ciphertext LONGTEXT NOT NULL,
		is_active TINYINT(1) NOT NULL DEFAULT 0,
		last_tested_at DATETIME NULL,
		last_test_error TEXT NOT NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS oci_runtime_settings (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		compartment_ocid VARCHAR(255) NOT NULL DEFAULT '',
		availability_domain VARCHAR(255) NOT NULL DEFAULT '',
		subnet_ocid VARCHAR(255) NOT NULL DEFAULT '',
		nsg_ocids_json LONGTEXT NOT NULL,
		image_ocid VARCHAR(255) NOT NULL DEFAULT '',
		assign_public_ip TINYINT(1) NOT NULL DEFAULT 0,
		cache_compat_enabled TINYINT(1) NOT NULL DEFAULT 0,
		cache_bucket_name VARCHAR(255) NOT NULL DEFAULT '',
		cache_object_prefix VARCHAR(255) NOT NULL DEFAULT '',
		cache_retention_days INT NOT NULL DEFAULT 7,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS github_configs (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		name VARCHAR(255) NOT NULL DEFAULT '',
		tags_json LONGTEXT NOT NULL,
		api_base_url VARCHAR(255) NOT NULL DEFAULT '',
		auth_mode VARCHAR(16) NOT NULL DEFAULT 'app',
		app_id BIGINT NOT NULL DEFAULT 0,
		installation_id BIGINT NOT NULL DEFAULT 0,
		private_key_ciphertext LONGTEXT NOT NULL,
		webhook_secret_ciphertext LONGTEXT NOT NULL,
		allowed_org VARCHAR(255) NOT NULL DEFAULT '',
		allowed_repos_json LONGTEXT NOT NULL,
		account_login VARCHAR(255) NOT NULL DEFAULT '',
		account_type VARCHAR(64) NOT NULL DEFAULT '',
		installation_state VARCHAR(32) NOT NULL DEFAULT '',
		installation_repository_selection VARCHAR(32) NOT NULL DEFAULT '',
		installation_repositories_json LONGTEXT NOT NULL,
		is_active TINYINT(1) NOT NULL DEFAULT 0,
		is_staged TINYINT(1) NOT NULL DEFAULT 0,
		last_tested_at DATETIME NULL,
		last_test_error TEXT NOT NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS github_pending_manifests (
		session_binding VARCHAR(255) NOT NULL,
		app_id BIGINT NOT NULL,
		app_name VARCHAR(255) NOT NULL DEFAULT '',
		app_slug VARCHAR(255) NOT NULL DEFAULT '',
		app_settings_url VARCHAR(512) NOT NULL DEFAULT '',
		transfer_url VARCHAR(512) NOT NULL DEFAULT '',
		install_url VARCHAR(512) NOT NULL DEFAULT '',
		owner_target VARCHAR(32) NOT NULL DEFAULT '',
		private_key_ciphertext LONGTEXT NOT NULL,
		webhook_secret_ciphertext LONGTEXT NOT NULL,
		created_at DATETIME NOT NULL,
		expires_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL,
		UNIQUE KEY github_pending_manifests_session_binding (session_binding)
	)`,
	`CREATE TABLE IF NOT EXISTS github_route_installation_statuses (
		api_base_url VARCHAR(255) NOT NULL,
		app_id BIGINT NOT NULL DEFAULT 0,
		installation_id BIGINT NOT NULL DEFAULT 0,
		account_login VARCHAR(255) NOT NULL DEFAULT '',
		account_type VARCHAR(64) NOT NULL DEFAULT '',
		installation_state VARCHAR(32) NOT NULL DEFAULT '',
		installation_repository_selection VARCHAR(32) NOT NULL DEFAULT '',
		installation_repositories_json LONGTEXT NOT NULL,
		last_tested_at DATETIME NULL,
		last_test_error TEXT NOT NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL,
		PRIMARY KEY (api_base_url, app_id, installation_id)
	)`,
	`CREATE TABLE IF NOT EXISTS runner_image_recipes (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		name VARCHAR(255) NOT NULL UNIQUE,
		description TEXT NOT NULL,
		base_image_ocid VARCHAR(255) NOT NULL DEFAULT '',
		subnet_ocid VARCHAR(255) NOT NULL DEFAULT '',
		shape VARCHAR(128) NOT NULL,
		ocpu INT NOT NULL,
		memory_gb INT NOT NULL,
		image_display_name VARCHAR(255) NOT NULL DEFAULT '',
		setup_commands_json LONGTEXT NOT NULL,
		verify_commands_json LONGTEXT NOT NULL,
		promoted_build_id BIGINT NULL,
		promoted_image_ocid VARCHAR(255) NOT NULL DEFAULT '',
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS runner_image_builds (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		recipe_id BIGINT NOT NULL,
		recipe_name VARCHAR(255) NOT NULL,
		status VARCHAR(64) NOT NULL,
		status_message TEXT NOT NULL,
		error_message TEXT NOT NULL,
		base_image_ocid VARCHAR(255) NOT NULL DEFAULT '',
		subnet_ocid VARCHAR(255) NOT NULL DEFAULT '',
		shape VARCHAR(128) NOT NULL,
		ocpu INT NOT NULL,
		memory_gb INT NOT NULL,
		image_display_name VARCHAR(255) NOT NULL DEFAULT '',
		setup_commands_json LONGTEXT NOT NULL,
		verify_commands_json LONGTEXT NOT NULL,
		instance_ocid VARCHAR(255) NOT NULL DEFAULT '',
		image_ocid VARCHAR(255) NOT NULL DEFAULT '',
		launched_at DATETIME NULL,
		completed_at DATETIME NULL,
		promoted_at DATETIME NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`ALTER TABLE policies ADD COLUMN subnet_ocid VARCHAR(255) NOT NULL DEFAULT ''`,
	`ALTER TABLE policies ADD COLUMN warm_enabled TINYINT(1) NOT NULL DEFAULT 0`,
	`ALTER TABLE policies ADD COLUMN warm_min_idle INT NOT NULL DEFAULT 0`,
	`ALTER TABLE policies ADD COLUMN warm_ttl_minutes INT NOT NULL DEFAULT 0`,
	`ALTER TABLE policies ADD COLUMN warm_repo_allowlist_json LONGTEXT NULL`,
	`UPDATE policies SET warm_repo_allowlist_json = '[]' WHERE warm_repo_allowlist_json IS NULL`,
	`ALTER TABLE policies MODIFY COLUMN warm_repo_allowlist_json LONGTEXT NOT NULL`,
	`ALTER TABLE policies ADD COLUMN budget_enabled TINYINT(1) NOT NULL DEFAULT 0`,
	`ALTER TABLE policies ADD COLUMN budget_cap_amount DOUBLE NOT NULL DEFAULT 0`,
	`ALTER TABLE policies ADD COLUMN budget_window_days INT NOT NULL DEFAULT 7`,
	`ALTER TABLE github_configs ADD COLUMN auth_mode VARCHAR(16) NOT NULL DEFAULT 'app'`,
	`ALTER TABLE github_configs ADD COLUMN account_login VARCHAR(255) NOT NULL DEFAULT ''`,
	`ALTER TABLE github_configs ADD COLUMN account_type VARCHAR(64) NOT NULL DEFAULT ''`,
	`ALTER TABLE github_configs ADD COLUMN installation_state VARCHAR(32) NOT NULL DEFAULT ''`,
	`ALTER TABLE github_configs ADD COLUMN installation_repository_selection VARCHAR(32) NOT NULL DEFAULT ''`,
	`ALTER TABLE github_configs ADD COLUMN installation_repositories_json LONGTEXT NULL`,
	`UPDATE github_configs SET installation_repositories_json = '[]' WHERE installation_repositories_json IS NULL`,
	`ALTER TABLE github_configs MODIFY COLUMN installation_repositories_json LONGTEXT NOT NULL`,
	`ALTER TABLE github_configs ADD COLUMN is_staged TINYINT(1) NOT NULL DEFAULT 0`,
	`ALTER TABLE github_configs ADD COLUMN name VARCHAR(255) NOT NULL DEFAULT ''`,
	`ALTER TABLE github_configs ADD COLUMN tags_json LONGTEXT NULL`,
	`UPDATE github_configs SET tags_json = '[]' WHERE tags_json IS NULL`,
	`ALTER TABLE github_configs MODIFY COLUMN tags_json LONGTEXT NOT NULL`,
	`ALTER TABLE jobs ADD COLUMN github_config_id BIGINT NOT NULL DEFAULT 0`,
	`ALTER TABLE jobs ADD COLUMN github_config_name VARCHAR(255) NOT NULL DEFAULT ''`,
	`ALTER TABLE jobs ADD COLUMN github_config_tags_json LONGTEXT NULL`,
	`UPDATE jobs SET github_config_tags_json = '[]' WHERE github_config_tags_json IS NULL`,
	`ALTER TABLE jobs MODIFY COLUMN github_config_tags_json LONGTEXT NOT NULL`,
	`ALTER TABLE runners ADD COLUMN github_config_id BIGINT NOT NULL DEFAULT 0`,
	`ALTER TABLE runners ADD COLUMN github_config_name VARCHAR(255) NOT NULL DEFAULT ''`,
	`ALTER TABLE runners ADD COLUMN github_config_tags_json LONGTEXT NULL`,
	`UPDATE runners SET github_config_tags_json = '[]' WHERE github_config_tags_json IS NULL`,
	`ALTER TABLE runners MODIFY COLUMN github_config_tags_json LONGTEXT NOT NULL`,
	`ALTER TABLE runners ADD COLUMN source VARCHAR(32) NOT NULL DEFAULT 'ondemand'`,
	`ALTER TABLE runners ADD COLUMN warm_state VARCHAR(32) NOT NULL DEFAULT ''`,
	`ALTER TABLE runners ADD COLUMN warm_policy_id BIGINT NULL`,
	`ALTER TABLE runners ADD COLUMN warm_repo_owner VARCHAR(128) NOT NULL DEFAULT ''`,
	`ALTER TABLE runners ADD COLUMN warm_repo_name VARCHAR(128) NOT NULL DEFAULT ''`,
	`ALTER TABLE oci_runtime_settings ADD COLUMN cache_compat_enabled TINYINT(1) NOT NULL DEFAULT 0`,
	`ALTER TABLE oci_runtime_settings ADD COLUMN cache_bucket_name VARCHAR(255) NOT NULL DEFAULT ''`,
	`ALTER TABLE oci_runtime_settings ADD COLUMN cache_object_prefix VARCHAR(255) NOT NULL DEFAULT ''`,
	`ALTER TABLE oci_runtime_settings ADD COLUMN cache_retention_days INT NOT NULL DEFAULT 7`,
	`CREATE TABLE IF NOT EXISTS job_diagnostics (
		job_id BIGINT PRIMARY KEY,
		delivery_id VARCHAR(128) NOT NULL DEFAULT '',
		summary_code VARCHAR(128) NOT NULL DEFAULT '',
		blocking_stage VARCHAR(64) NOT NULL DEFAULT '',
		matched_policy_id BIGINT NULL,
		runner_id BIGINT NULL,
		instance_ocid VARCHAR(255) NOT NULL DEFAULT '',
		stage_statuses_json LONGTEXT NOT NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS billing_policy_snapshots (
		policy_id BIGINT NOT NULL,
		window_days INT NOT NULL,
		currency VARCHAR(32) NOT NULL DEFAULT '',
		total_cost DOUBLE NOT NULL DEFAULT 0,
		generated_at DATETIME NOT NULL,
		source_region VARCHAR(64) NOT NULL DEFAULT '',
		error_message TEXT NOT NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL,
		PRIMARY KEY (policy_id, window_days)
	)`,
	`CREATE TABLE IF NOT EXISTS cache_entries (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		repo_owner VARCHAR(128) NOT NULL,
		repo_name VARCHAR(128) NOT NULL,
		cache_key VARCHAR(512) NOT NULL,
		cache_version VARCHAR(255) NOT NULL,
		object_name VARCHAR(1024) NOT NULL,
		size_bytes BIGINT NOT NULL DEFAULT 0,
		created_at DATETIME NOT NULL,
		last_accessed_at DATETIME NOT NULL,
		expires_at DATETIME NULL,
		UNIQUE KEY cache_entries_lookup (repo_owner, repo_name, cache_key(255), cache_version)
	)`,
	`CREATE TABLE IF NOT EXISTS http_rate_limits (
		scope VARCHAR(64) NOT NULL,
		client_ip VARCHAR(255) NOT NULL,
		window_started DATETIME NOT NULL,
		expires_at DATETIME NOT NULL,
		request_count INT NOT NULL DEFAULT 0,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL,
		PRIMARY KEY (scope, client_ip, window_started)
	)`,
}
